---
title: "cuarto_dia"
author: "I. Bartomeus"
date: "26 February 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Instalo y cargo el paquete ggplot2.
```{r, warning = FALSE}
#install.packages("ggplot2")
library(ggplot2)

p = ggplot(data=bond, aes(x=Year, y=tomatoRotten)) +  #que quiero representar
      geom_point()                                    #como lo quiero representar
p
summary(p)

#color por variable
p = ggplot(data=bond, aes(x=Year, y=tomatoRotten, 
                          color = Actor_p)) +  
      geom_point()                             
p
#color homogeneo
p = ggplot(data=bond, aes(x=Year, y=tomatoRotten)) +  
      geom_point(color="steelblue", size=4, alpha=1/2)                          
p
#tamaño y forma
ggplot(data=bond, aes(x=Year, y=tomatoRotten, 
                          size = Actor_p)) +  
      geom_point()                             
ggplot(data=bond, aes(x=Year, y=tomatoRotten, 
                          shape = Actor_p)) +  
      geom_point()                             

#añadir estadistica directamente
ggplot(data=bond, aes(x=Year, y=tomatoRotten)) +  
  geom_point() +
  geom_smooth()  #El sombreado representa el error estandar.
#o con modelo linear
ggplot(data=bond, aes(x=Year, y=tomatoRotten)) +  
  geom_point() +
  geom_smooth(method="lm", se=TRUE)
#y por color!
ggplot(data=bond, aes(x=Year, y=tomatoRotten, color = Actor_p)) +  
  geom_point() +
  geom_smooth(method="lm", se=TRUE)
#Prueba quitar los puntos, o cambiar el tipo de linea...

#O dividir por paneles
ggplot(data=bond, aes(x=Year, y=tomatoRotten)) +  
  geom_point() +
  geom_smooth(method="lm", se=TRUE) +
  facet_wrap(~ Actor_p)

help(facet_wrap)


#para las anotaciones añadimos capas:
ggplot(data=bond, aes(x=Year, y=tomatoRotten)) +  
  geom_point() +
  ggtitle("La decadencia de 007") +
  xlab("Año") +
  ylab("Tomates recibidos")

#y si no te gusta el tema?
ggplot(data=bond, aes(x=Year, y=tomatoRotten)) +  
  geom_point() +
  theme_bw() # Tema predefinido. Cambia algunos valores por defecto (color de fondo, de las fuentes..).

help(theme)

#Y tiene mil geom's
#e.g. histograma
ggplot(data=bond, aes(x=tomatoRotten)) +  
  geom_histogram()

#density
ggplot(data=bond, aes(x=tomatoRotten, color = Actor_p)) +  
  geom_density() + 
  ylim(c(0, 0.10))

#boxplots
ggplot(data=bond, aes(Actor_p,tomatoRotten)) +  
  geom_boxplot()

ggplot(data=bond, aes(Actor_p,tomatoRotten)) +  
  geom_violin()

#guardar graficos

jpeg(filename="007.jpeg",   # Nombre del archivo y extension
     height = 11,
     width = 18,
     res= 200,       # Resolucion
     units = "cm")   # Unidades.
p           # Grafico
dev.off()            # Cierre del archivo
```


Ejercicio dplyr
```{r}

#usar pipes (this is not a %>% )
sombras <- function(n){
  seq(0,1, length.out = n)  
}

grey(sombras(50))

library(dplyr)
50 %>%  sombras %>% grey #shift cmd M

# agregar datos
# ya hemos visto la familia de tapply

#aggregate es lento y poco flexible

# La peor puntuación de cada actor?
aggregate(tomatoRotten ~ Actor_p, 
          data = bond, FUN = max)

# dplyr como sintaxis
# Verbos
#* `filter()` - subset rows; like `base::subset()`
#* `arrange()` - reorder rows; like `order()`
#* `select()` - select columns
#* `mutate()` - add new columns
#* `summarise()` - like `aggregate`

#Grouping
bond %>% 
  group_by(Actor_p) %>% 
  summarise(max(tomatoRotten))

#por si quereis practicar con otro dataset interesante
install.packages("babynames")
library(babynames)
babynames %>% group_by(year, sex)
```


MergeMerging datasets
========================================================
  

```{r, echo=FALSE}
howpretty <- data.frame(Actor_p = unique(bond$Actor_p), 
                        pretty = c("feo", "resulton", "guaperas",
                                   "feo", "resulton", "guaperas"))
howpretty

#merge (funcione base)
bond <- merge(bond, howpretty)

#The `dplyr` package tiene otras funciones más rápidas y flexibles de merge "join"

```


Reshape!
---------------

```{r}

# Por último hay veces que queremos transformar datos y table() se queda corto.
library(reshape2)

#Basically, you "melt" data so that each row is a unique id-variable combination. Then you "dcast" the melted data into any shape you would like. Here is a very simple example.

head(bond)
dcast(bond, Actor_p ~ pretty, value.var = "tomatoRotten", max)
dcast(bond, Actor_p ~ pretty, value.var = "tomatoRotten", mean)

#melt() crea datos "tidy". Todos vuestros datos habrian de ser tidy.

```




