---
title: "James Bond: 007"
author: "I. Bartomeus"
date: "23 Febrero 2016"
output: html_document
---
  
  
James Bond: realmente mola mogoll칩n?
------------------------------------

```{r, echo=FALSE} 

#leer datos de peliculas de James Bond en la carpeta datos con la funci칩n read.table o read.csv
bond <- read.csv("Rbasics/ejercicios/data/007.csv")
#bond <- read.table("Rbasics/ejercicios/data/007.csv", header = TRUE, sep = ",")

#No explico attach, por que mejor no lo usamos!

#explorar los datos
str(bond) #data.frame!
head(bond)
#facors
levels(bond$Actors)

#limpiar datos
colnames(bond)
#eliminar la ultima columna: index
bond2 <- bond[,-35]
bond2 <- bond[,-"Response"]
bond2 <- subset(bond, select = -Response)
#subset
bond[which(bond$Year > 2000),]
subset(bond, Year > 2000)

#rescatar actor principal #grep y substr
bond$Actor_p <- substr(bond$Actor, 1, regexpr(pattern = ",", bond$Actor)-1)

#guardar datos

#write.table(bond, "Rbasics/ejercicios/data/007_edited.csv")
#write.csv()
#save(bond, file = "Rbasics/ejercicios/data/007_edited.R") #Rdata
#rm(bond)
#load("Rbasics/ejercicios/data/007_edited.R")
  
# Funciones que necesitaremos SE

se <- function(x){sd(x)/sqrt(length(x))}
se(c(3,4,6,4))

```

** Pregunta: ** Gusta 007?

```{r, echo = FALSE}

#boxplot de imdbRating
boxplot(bond$imdbRating)

# y lo ponemos bonito
boxplot(bond$imdbRating, las = 1, main = "IMDB rating")
# a침adimos tomatoUserRating
boxplot(bond$imdbRating, bond$tomatoUserRating, las = 1, names = c("IMDB", "Tomatoes"),
        main = "Rating", ylim = c(0,10))
abline(h = 5, lty = 2)

#boxplots esconden cosas
boxplot(bond$imdbRating, las = 1, main = "IMDB rating", cex = 0)
points(mean(bond$imdbRating), pch = 19, col = "red")
points(jitter(rep(1, length(bond$imdbRating)), 4), bond$imdbRating)
```

Aun gusta es el agente 007?

```{r, echo = FALSE}
# Que opina la gente imdbRating
plot(bond$Year, bond$imdbRating)
scatter.smooth(bond$Year, bond$imdbRating)
# Y que opina la citica tomatoRotten #https://en.wikipedia.org/wiki/Rotten_Tomatoes
plot(bond$Year, bond$tomatoRotten)
plot(bond$Year, 100 - bond$tomatoRotten)
scatter.smooth(bond$Year, 100 - bond$tomatoRotten)

# R puede hacer pie charts, pero no los useis
#pie()

```

Y que actor esta mejor valorado?
  
```{r, echo = FALSE}
mean_ratings <- tapply(bond$imdbRating, bond$Actor_p, mean)
mean_ratings <- sort(mean_ratings, decreasing = TRUE)
bp <- barplot(mean_ratings, las = 1, ylim = c(0,10))
#a침adimos SE
se_ratings <- tapply(bond$imdbRating, bond$Actor_p, se)
#ordenar igual
se_ratings <- se_ratings[names(sort(mean_ratings, decreasing = TRUE))]
arrows(x0 = bp,
       x1 = bp,
       y0 = mean_ratings - se_ratings,
       y1 = mean_ratings + se_ratings,
       las = 1, angle = 90, code = 3)

```

Y unas tablas

```{r, echo = FALSE}
# resumen e una variable
summary(bond$Year)

table(bond$Year, bond$Actor_p)

```









